# -*- coding: utf-8 -*-
"""maya.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14DUgAaf5QywMNnIvIL7KlWQ95-bPE1WV
"""

from IPython.display import display, HTML

html_code = """
<div style="font-family: 'Segoe UI', Helvetica, Arial, sans-serif; max-width: 950px; margin: 0 auto; background-color: #0f172a; padding: 25px; border-radius: 16px; color: #1e293b;">

  <!-- CONTENEDOR PRINCIPAL BLANCO -->
  <div style="background-color: #f8fafc; border-radius: 12px; padding: 35px 40px; box-shadow: 0 10px 25px rgba(0,0,0,0.3);">

    <!-- ENCABEZADO -->
    <div style="text-align: center; border-bottom: 2px solid #cbd5e1; padding-bottom: 20px; margin-bottom: 25px;">
      <h1 style="color: #0f172a; font-size: 26px; font-weight: 800; margin: 0 0 10px 0; letter-spacing: -0.5px;">
        REDES NEURONALES VIGESIMALES (MVN)
      </h1>
      <p style="color: #475569; font-size: 15px; margin: 0 0 18px 0; font-weight: 500;">
        Simulación de Perceptrones Mediante Aritmética Biquinaria Maya y Aritmética Posicional Discreta
      </p>

      <!-- BADGES -->
      <div style="display: flex; justify-content: center; gap: 10px; flex-wrap: wrap;">
        <span style="background: #f97316; color: white; padding: 4px 12px; border-radius: 6px; font-size: 11px; font-weight: 700;">COLAB READY</span>
        <span style="background: #3b82f6; color: white; padding: 4px 12px; border-radius: 6px; font-size: 11px; font-weight: 700;">PYTHON 3.10+</span>
        <span style="background: #059669; color: white; padding: 4px 12px; border-radius: 6px; font-size: 11px; font-weight: 700;">ETHNOMATHEMATICS | EDGE AI</span>
        <span style="background: #64748b; color: white; padding: 4px 12px; border-radius: 6px; font-size: 11px; font-weight: 700;">LICENCIA MIT</span>
      </div>
    </div>

    <!-- SECCIÓN: CRÉDITOS Y AUTORÍA -->
    <div style="border: 1px solid #cbd5e1; border-radius: 8px; overflow: hidden; margin-bottom: 25px; background: #f1f5f9;">
      <div style="background: #0f172a; color: white; padding: 8px 16px; font-weight: 700; font-size: 12px; letter-spacing: 0.5px;">
        CRÉDITOS Y DIRECCIÓN DE INVESTIGACIÓN
      </div>
      <div style="padding: 16px 20px; display: grid; grid-template-columns: 1fr 1fr; gap: 25px;">
        <div>
          <div style="font-size: 12px; font-weight: 700; color: #475569; margin-bottom: 4px;">Investigación, Diseño Conceptual y Dirección Metodológica:</div>
          <div style="font-size: 16px; font-weight: 800; color: #0f766e; margin-bottom: 4px;">Eduardo Alejandro Riveros Quiroz</div>
          <div style="font-size: 12px; color: #64748b; font-style: italic;">Formulación de la hipótesis interdisciplinaria, arquitectura experimental, modelado pedagógico y validación analítica.</div>
        </div>
        <div>
          <div style="font-size: 12px; font-weight: 700; color: #475569; margin-bottom: 4px;">Soporte de Prototipado e Implementación de Código:</div>
          <div style="font-size: 15px; font-weight: 700; color: #1e293b; margin-bottom: 4px;">Asistencia Algorítmica Guiada Mediante IA</div>
          <div style="font-size: 12px; color: #64748b; font-style: italic;">Co-programación y síntesis de operadores discretos bajo la dirección del autor principal (Gemini, Google).</div>
        </div>
      </div>
    </div>

    <!-- SECCIÓN 1: RESUMEN EJECUTIVO -->
    <div style="border: 1px solid #bfdbfe; border-radius: 8px; overflow: hidden; margin-bottom: 25px; background: white;">
      <div style="background: #1e3a8a; color: white; padding: 8px 16px; font-weight: 700; font-size: 12px; letter-spacing: 0.5px;">
        1. RESUMEN EJECUTIVO (ABSTRACT)
      </div>
      <div style="padding: 18px 20px; font-size: 13.5px; line-height: 1.6; color: #334155;">
        <p style="margin: 0 0 12px 0;">
          Este proyecto formaliza y evalúa la viabilidad de modelar arquitecturas de redes neuronales artificiales utilizando el sistema numérico vigesimal maya (base 20 con subsistema biquinario 5/1). Frente al estándar computacional dominante de punto flotante continuo (Base 10 / IEEE 754), se demuestra que la transformación lineal fundamental <strong>(z = &Sigma; w<sub>i</sub>x<sub>i</sub> + b)</strong> y las funciones de activación umbral (ReLU) pueden ejecutarse de manera nativa mediante operaciones aditivas discretas de unidades (puntos) y quinas (barras), integrando el caracol/semilla (<strong>0</strong>) como representación física del estado nulo o reposo de la neurona.
        </p>
        <p style="margin: 0; color: #0f766e; font-weight: 600;">
          Asimismo, se establece un puente conceptual entre el álgebra biquinaria mesoamericana y los métodos contemporáneos de cuantización extrema de redes neuronales (INT4 / INT8) y la computación neuromórfica para inferencia en el borde (Edge AI).
        </p>
      </div>
    </div>

    <!-- SECCIÓN 2: MARCO TEÓRICO -->
    <div style="border: 1px solid #a7f3d0; border-radius: 8px; overflow: hidden; margin-bottom: 25px; background: white;">
      <div style="background: #065f46; color: white; padding: 8px 16px; font-weight: 700; font-size: 12px; letter-spacing: 0.5px;">
        2. MARCO TEÓRICO Y JUSTIFICACIÓN EPISTÉMICA
      </div>
      <div style="padding: 18px 20px;">
        <div style="font-size: 13px; font-weight: 700; color: #064e3b; margin-bottom: 10px;">Dualidad del Aprendizaje Profundo Contemporáneo:</div>
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-bottom: 16px;">
          <div style="background: #eff6ff; border: 1px solid #93c5fd; padding: 12px; border-radius: 6px;">
            <div style="font-weight: 700; color: #1e40af; font-size: 12.5px; margin-bottom: 4px;">&bull; Fase Continua (Entrenamiento):</div>
            <div style="font-size: 12px; color: #1e3a8a; line-height: 1.4;">Precisión microscópica (FP32/FP16) para calcular gradientes infinitesimales mediante cálculo diferencial.</div>
          </div>
          <div style="background: #ecfdf5; border: 1px solid #6ee7b7; padding: 12px; border-radius: 6px;">
            <div style="font-weight: 700; color: #065f46; font-size: 12.5px; margin-bottom: 4px;">&bull; Fase Estructural Discreta (Inferencia):</div>
            <div style="font-size: 12px; color: #047857; line-height: 1.4;">Optimización energética en el borde mediante enteros pequeños sin degradar la capacidad de decisión.</div>
          </div>
        </div>

        <div style="font-size: 13px; font-weight: 700; color: #1e293b; margin-bottom: 8px;">Propiedades Computacionales del Sistema Maya:</div>
        <ul style="margin: 0; padding-left: 20px; font-size: 12.5px; color: #334155; line-height: 1.6;">
          <li><strong>Estructura Biquinaria Nativa:</strong> La base auxiliar 5 transforma la multiplicación matricial en sumas aditivas directas antes del acarreo.</li>
          <li><strong>Densidad de Estados:</strong> Cada posición almacena de 0 a 19 (~4.32 bits), mapeando INT4 con exactitud directa.</li>
          <li><strong>Dualidad Líquido vs. Bloques:</strong> El número pasa de "volumen analógico" (agua) a "estructura ensamblable" (LEGO).</li>
        </ul>
      </div>
    </div>

    <!-- SECCIÓN 3 Y 4: METODOLOGÍA Y ENTORNO -->
    <div style="display: grid; grid-template-columns: 2fr 1fr; gap: 20px;">
      <!-- Metodología -->
      <div style="border: 1px solid #c7d2fe; border-radius: 8px; overflow: hidden; background: white;">
        <div style="background: #4338ca; color: white; padding: 8px 16px; font-weight: 700; font-size: 12px;">
          3. METODOLOGÍA EXPERIMENTAL
        </div>
        <div style="padding: 16px; font-size: 12px; color: #334155; line-height: 1.5;">
          <div style="margin-bottom: 8px;"><strong>1. Formalización Aritmética:</strong> Modelado de barras y puntos con acarreos en potencias 20<sup>k</sup>.</div>
          <div style="margin-bottom: 8px;"><strong>2. Perceptrón Unario:</strong> Clasificador de spam con pesos inhibitorios y sesgo de inocencia.</div>
          <div style="margin-bottom: 8px;"><strong>3. Red Multicapa en Cascada:</strong> Desacople jerárquico de variables (clima + energía) para decisiones complejas.</div>
          <div><strong>4. Validación Cruzada:</strong> Replicación paramétrica en Python base 10 para comprobar equivalencia funcional.</div>
        </div>
      </div>

      <!-- Entorno -->
      <div style="border: 1px solid #cbd5e1; border-radius: 8px; overflow: hidden; background: white;">
        <div style="background: #334155; color: white; padding: 8px 16px; font-weight: 700; font-size: 12px;">
          4. ENTORNO Y EJECUCIÓN
        </div>
        <div style="padding: 16px; font-size: 12px;">
          <div style="color: #475569; margin-bottom: 10px;">
            &bull; Google Colab / Python 3.10+<br>
            &bull; Matplotlib >= 3.7.0
          </div>
          <div style="background: #0f172a; color: #38bdf8; font-family: monospace; padding: 10px; border-radius: 6px; font-size: 11px; margin-bottom: 10px;">
            $ pip install matplotlib
          </div>
          <div style="background: #fef3c7; color: #92400e; border: 1px solid #f59e0b; padding: 6px; border-radius: 6px; text-align: center; font-weight: 700; font-size: 11px;">
            ESTADO: VALIDADO
          </div>
        </div>
      </div>
    </div>

    <!-- PIE DE TARJETA -->
    <div style="text-align: center; margin-top: 25px; padding-top: 15px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; font-style: italic;">
      Cuaderno de Investigación Abierta — Intersección entre Etnomatemática, Álgebra Discreta e Inteligencia Artificial
    </div>

  </div>
</div>
"""

display(HTML(html_code))



import matplotlib.pyplot as plt

# 1. Configurar lienzo
fig, ax = plt.subplots(figsize=(13, 6.8), dpi=300)
ax.axis("off")

# 2. Título y subtítulo pedagógico
plt.suptitle(
    "ANÁLISIS COMPARATIVO: REDES NEURONALES",
    fontsize=16,
    fontweight="bold",
    y=0.96,
    color="#1E293B"
)
plt.title(
    "Matemática Occidental (Base 10 / Continuo) vs. Matemática Maya (Base 20 / Discreto Biquinario)",
    fontsize=11,
    color="#475569",
    pad=16
)

# 3. Datos de la tabla comparativa
columnas = [
    "Criterio",
    "Enfoque Occidental\n(Base 10 / Punto Flotante IEEE 754)",
    "Enfoque Maya\n(Base 20 / Biquinario Posicional)"
]

filas = [
    [
        "Naturaleza del\nNúmero",
        "Continuo (como agua en un vaso).\nAdmite infinitos decimales (ej. 7.0034...).",
        "Discreto (como bloques de LEGO).\nPiezas enteras indivisibles: puntos (1) y barras (5)."
    ],
    [
        "Representación\ndel Estado",
        "Escalar abstracto en memoria (float32/float64).\nSímbolo numérico arábigo arbitrario.",
        "Estructura geométrica visual tangible.\nSe construye apilando piedritas y varillas de madera."
    ],
    [
        "Concepto del Cero",
        "Cero algebraico de escala (0.0).\nUn punto intermedio en la recta numérica.",
        "El Caracol / Semilla (𝄐).\nEstado de reposo absoluto: el cuenco está vacío."
    ],
    [
        "Mecanismo de\nCálculo (MAC)",
        "Multiplicadores binarios en hardware de silicio.\nOperaciones lógicas por desplazamiento y suma interna.",
        "Ábaco aditivo directo (estilo Nepohualtzintzin).\n5 puntos se reemplazan por 1 barra; 4 barras hacen nivel 20."
    ],
    [
        "Paralelismo con la\nIA Actual",
        "Entrenamiento tradicional con backpropagation\npreciso en FP16/FP32.",
        "Cuantización extrema de pesos e inferencia de borde:\nINT4 / INT8 y computación neuromórfica por pulsos."
    ]
]

# 4. Construcción y formato de la tabla
tabla = ax.table(
    cellText=filas,
    colLabels=columnas,
    loc="center",
    cellLoc="left"
)

tabla.auto_set_font_size(False)
tabla.set_fontsize(9.5)
tabla.scale(1.0, 2.2)

# 5. Estilización visual (encabezados, bordes y zebra striping)
header_color = "#0F172A"       # Azul pizarra oscuro
col1_bg = "#F8FAFC"            # Gris hielo claro
col2_bg = "#EFF6FF"            # Azul muy suave (Occidental)
col3_bg = "#FEF3C7"            # Tono cálido/dorado suave (Maya)

for (row, col), cell in tabla.get_celld().items():
    cell.set_edgecolor("#CBD5E1")
    cell.set_linewidth(1.0)

    if row == 0:
        # Encabezado
        cell.set_facecolor(header_color)
        cell.set_text_props(color="white", weight="bold", ha="center")
    else:
        # Contenido
        if col == 0:
            cell.set_facecolor(col1_bg)
            cell.set_text_props(weight="bold", color="#334155")
        elif col == 1:
            cell.set_facecolor(col2_bg)
            cell.set_text_props(color="#1E293B")
        elif col == 2:
            cell.set_facecolor(col3_bg)
            cell.set_text_props(color="#78350F")

# 6. Guardar archivo local en Colab
plt.tight_layout()
plt.savefig("comparativa_maya_occidental.png", dpi=300, bbox_inches="tight")
plt.show()

print("✓ Imagen generada y guardada como 'comparativa_maya_occidental.png'")

import matplotlib.pyplot as plt
import matplotlib.patches as patches

# 1. Configuración de lienzo de alta resolución
fig, ax = plt.subplots(figsize=(13, 7.2), dpi=300)
ax.axis("off")
ax.set_xlim(0, 100)
ax.set_ylim(0, 100)

# 2. Título principal y subtítulo
ax.text(
    50, 93,
    "LA ANALOGÍA DEFINITIVA: LÍQUIDO VS. LEGOS",
    fontsize=16, fontweight="bold", ha="center", color="#0F172A"
)
ax.text(
    50, 88.5,
    "Dos formas conceptualmente opuestas de procesar información en una neurona artificial",
    fontsize=11, ha="center", color="#475569"
)

# 3. Función auxiliar para dibujar tarjetas redondeadas
def dibujar_tarjeta(x, y, w, h, bg_color, border_color):
    rect = patches.FancyBboxPatch(
        (x, y), w, h,
        boxstyle="round,pad=0,rounding_size=2.5",
        linewidth=1.5,
        edgecolor=border_color,
        facecolor=bg_color
    )
    ax.add_patch(rect)

# 4. Tarjeta Izquierda: Enfoque Occidental (Líquido)
dibujar_tarjeta(x=4, y=6, w=44, h=78, bg_color="#F0F7FF", border_color="#3B82F6")

# Cabecera Tarjeta Occidental
ax.text(26, 79, "RED NEURONAL OCCIDENTAL", fontsize=12, fontweight="bold", ha="center", color="#1E40AF")
ax.text(26, 75, "«El número como agua en un vaso»", fontsize=10.5, fontstyle="italic", ha="center", color="#3B82F6")

# Puntos clave Occidental
items_occ = [
    ("Naturaleza Continua:", "Los valores fluyen sin saltos. Entre el 6 y el 7\nhay infinitos números posibles (ej. 6.873)."),
    ("Medición y Precisión:", "Equivale a un vaso graduado de laboratorio.\nSe ajusta con precisión decimal microscópica."),
    ("Operación de Ajuste:", "Funciona como una perilla o válvula giratoria:\nse abre o cierra en fracciones suaves."),
    ("El Cero (0.0):", "Es simplemente la marca mínima en la escala.\nUn punto neutro en una recta matemática infinita.")
]

y_pos = 66
for titulo, desc in items_occ:
    ax.text(7, y_pos, f"• {titulo}", fontsize=10, fontweight="bold", color="#1E3A8A")
    ax.text(9, y_pos - 4.5, desc, fontsize=9.2, color="#334155")
    y_pos -= 14

# 5. Tarjeta Derecha: Enfoque Maya (Legos)
dibujar_tarjeta(x=52, y=6, w=44, h=78, bg_color="#FEFCE8", border_color="#EAB308")

# Cabecera Tarjeta Maya
ax.text(74, 79, "RED NEURONAL MAYA", fontsize=12, fontweight="bold", ha="center", color="#854D0E")
ax.text(74, 75, "«El número como bloques de LEGO»", fontsize=10.5, fontstyle="italic", ha="center", color="#CA8A04")

# Puntos clave Maya
items_maya = [
    ("Naturaleza Discreta:", "Los valores van a saltos completos.\nNo existen fracciones de punto ni pedazos de barra."),
    ("Estructura en Fichas:", "Se construye apilando piezas físicas:\n• Puntos = piezas de 1 botón\n— Rayas = barras de 5 botones"),
    ("Operación de Ajuste:", "Se agregan o retiran bloques completos.\nAl juntar 5 puntos, se transforman en una barra."),
    ("El Cero (Caracol 𝄐):", "El cuenco está completamente vacío.\nAusencia de piezas: reposo absoluto del circuito.")
]

y_pos = 66
for titulo, desc in items_maya:
    ax.text(55, y_pos, f"• {titulo}", fontsize=10, fontweight="bold", color="#713F12")
    ax.text(57, y_pos - 4.5, desc, fontsize=9.2, color="#422006")
    y_pos -= 14

# 6. Conclusión en la base
ax.text(
    50, 2,
    "Conclusión: Ambas arquitecturas calculan la misma función (z = w · x + b). "
    "Occidente mide volúmenes analógicos; el sistema maya apila bloques estructurales.",
    fontsize=9.3, ha="center", style="italic", color="#64748B"
)

# 7. Guardar y mostrar
plt.tight_layout()
plt.savefig("analogia_liquido_vs_legos.png", dpi=300, bbox_inches="tight")
plt.show()

print("✓ Imagen generada y guardada como 'analogia_liquido_vs_legos.png'")