# -*- coding: utf-8 -*-
"""maya.ipynb

Automatically generated by Colab.

Original file is located at
    https://google.com
"""

import math
import random
from typing import List, Tuple
from IPython.display import display, HTML
import matplotlib.pyplot as plt
import matplotlib.patches as patches

# ======================================================================
# INTERFAZ ACADÉMICA INTERACTIVA (HTML EMBEBIDO)
# ======================================================================

html_code = """
<div style="font-family: 'Segoe UI', Helvetica, Arial, sans-serif; max-width: 950px; margin: 0 auto; background-color: #0f172a; padding: 25px; border-radius: 16px; color: #1e293b;">
  <div style="background-color: #f8fafc; border-radius: 12px; padding: 35px 40px; box-shadow: 0 10px 25px rgba(0,0,0,0.3);">
    
    <!-- ENCABEZADO -->
    <div style="text-align: center; border-bottom: 2px solid #cbd5e1; padding-bottom: 20px; margin-bottom: 25px;">
      <h1 style="color: #0f172a; font-size: 26px; font-weight: 800; margin: 0 0 10px 0; letter-spacing: -0.5px;">
        REDES NEURONALES VIGESIMALES (MVN)
      </h1>
      <p style="color: #475569; font-size: 15px; margin: 0 0 18px 0; font-weight: 500;">
        Simulación de Perceptrones Mediante Aritmética Biquinaria Maya y Aritmética Posicional Discreta
      </p>

      <!-- BADGES -->
      <div style="display: flex; justify-content: center; gap: 10px; flex-wrap: wrap;">
        <span style="background: #f97316; color: white; padding: 4px 12px; border-radius: 6px; font-size: 11px; font-weight: 700;">COLAB READY</span>
        <span style="background: #3b82f6; color: white; padding: 4px 12px; border-radius: 6px; font-size: 11px; font-weight: 700;">PYTHON 3.10+</span>
        <span style="background: #059669; color: white; padding: 4px 12px; border-radius: 6px; font-size: 11px; font-weight: 700;">ETHNOMATHEMATICS | EDGE AI</span>
        <span style="background: #64748b; color: white; padding: 4px 12px; border-radius: 6px; font-size: 11px; font-weight: 700;">LICENCIA GNU GPLv3</span>
      </div>
    </div>

    <!-- SECCIÓN: CRÉDITOS Y AUTORÍA -->
    <div style="border: 1px solid #cbd5e1; border-radius: 8px; overflow: hidden; margin-bottom: 25px; background: #f1f5f9;">
      <div style="background: #0f172a; color: white; padding: 8px 16px; font-weight: 700; font-size: 12px; letter-spacing: 0.5px;">
        CRÉDITOS Y DIRECCIÓN DE INVESTIGACIÓN
      </div>
      <div style="padding: 16px 20px; display: grid; grid-template-columns: 1fr 1fr; gap: 25px;">
        <div>
          <div style="font-size: 12px; font-weight: 700; color: #475569; margin-bottom: 4px;">Investigación, Diseño Conceptual y Dirección Metodológica:</div>
          <div style="font-size: 16px; font-weight: 800; color: #0f766e; margin-bottom: 4px;">Eduardo Alejandro Riveros Quiroz</div>
          <div style="font-size: 12px; color: #64748b; font-style: italic;">Formulación de la hipótesis interdisciplinaria, arquitectura experimental, modelado pedagógico y validación analítica.</div>
        </div>
        <div>
          <div style="font-size: 12px; font-weight: 700; color: #475569; margin-bottom: 4px;">Soporte de Prototipado e Implementación de Código:</div>
          <div style="font-size: 15px; font-weight: 700; color: #1e293b; margin-bottom: 4px;">Asistencia Algorítmica Guiada Mediante IA</div>
          <div style="font-size: 12px; color: #64748b; font-style: italic;">Co-programación y síntesis de operadores discretos bajo la dirección del autor principal (Gemini, Google).</div>
        </div>
      </div>
    </div>

    <!-- SECCIÓN 1: RESUMEN EJECUTIVO -->
    <div style="border: 1px solid #bfdbfe; border-radius: 8px; overflow: hidden; margin-bottom: 25px; background: white;">
      <div style="background: #1e3a8a; color: white; padding: 8px 16px; font-weight: 700; font-size: 12px; letter-spacing: 0.5px;">
        1. RESUMEN EJECUTIVO (ABSTRACT)
      </div>
      <div style="padding: 18px 20px; font-size: 13.5px; line-height: 1.6; color: #334155;">
        <p style="margin: 0 0 12px 0;">
          Este proyecto formaliza y evalúa la viabilidad de modelar arquitecturas de redes neuronales artificiales utilizando el sistema numérico vigesimal maya (base 20 con subsistema biquinario 5/1). Frente al estándar computacional dominante de punto flotante continuo (Base 10 / IEEE 754), se demuestra que la transformación lineal fundamental <strong>(z = &Sigma; w<sub>i</sub>x<sub>i</sub> + b)</strong> y las funciones de activación umbral (ReLU) pueden ejecutarse de manera nativa mediante operaciones aditivas discretas de unidades (puntos) y quinas (barras), integrando el caracol/semilla (<strong>0</strong>) como representación física del estado nulo o reposo de la neurona.
        </p>
      </div>
    </div>
  </div>
</div>
"""
display(HTML(html_code))

# ======================================================================
# GENERACIÓN DE GRÁFICOS ANALÓGICOS (MATPLOTLIB)
# ======================================================================

# Gráfico 1: Tabla Comparativa
fig, ax = plt.subplots(figsize=(13, 6.8), dpi=300)
ax.axis("off")
plt.suptitle("ANÁLISIS COMPARATIVO: REDES NEURONALES", fontsize=16, fontweight="bold", y=0.96, color="#1E293B")
plt.title("Matemática Occidental (Base 10) vs. Matemática Maya (Base 20 / Discreto Biquinario)", fontsize=11, color="#475569", pad=16)

columnas = ["Criterio", "Enfoque Occidental\n(Base 10 / IEEE 754)", "Enfoque Maya\n(Base 20 / Biquinario)"]
filas = [
    ["Naturaleza del Número", "Continuo (como agua en un vaso).\nAdmite infinitos decimales.", "Discreto (como bloques de LEGO).\nPiezas enteras indivisibles: puntos y barras."],
    ["Representación de Estado", "Escalar abstracto en memoria (float32/64).\nSímbolo numérico arbitrario.", "Estructura geométrica visual tangible.\nSe construye apilando varillas y piedritas."],
    ["Concepto del Cero", "Cero algebraico de escala (0.0).", "El Caracol / Semilla (𝄐).\nEstado de reposo absoluto: cuenco vacío."],
    ["Mecanismo de Cálculo", "Multiplicadores binarios en hardware de silicio.", "Ábaco aditivo directo (estilo Nepohualtzintzin)."],
    ["Paralelismo con IA Actual", "Entrenamiento tradicional con backpropagation.", "Cuantización extrema de pesos e inferencia de borde (INT4)."]
]

tabla = ax.table(cellText=filas, colLabels=columnas, loc="center", cellLoc="left")
tabla.auto_set_font_size(False)
tabla.set_fontsize(9.5)
tabla.scale(1.0, 2.2)

for (row, col), cell in tabla.get_celld().items():
    cell.set_edgecolor("#CBD5E1")
    if row == 0:
        cell.set_facecolor("#0F172A")
        cell.set_text_props(color="white", weight="bold", ha="center")
    else:
        if col == 0: cell.set_facecolor("#F8FAFC")
        elif col == 1: cell.set_facecolor("#EFF6FF")
        elif col == 2: cell.set_facecolor("#FEF3C7")

plt.tight_layout()
plt.savefig("comparativa_maya_occidental.png", dpi=300, bbox_inches="tight")
plt.close()

# ======================================================================
# 1. NÚCLEO ARITMÉTICO VIGESIMAL MAYA
# ======================================================================

class MayaScalar:
    """Escalar vigesimal entero representado con glifos biquinarios."""
    def __init__(self, val: int):
        self.val = int(val)
        self.sign = -1 if self.val < 0 else (1 if self.val > 0 else 0)
        mag = abs(self.val)
        
        self.levels: List[Tuple[int, int]] = []  # cada nivel guarda (barras, puntos)
        if mag == 0:
            self.levels.append((0, 0))
        else:
            while mag > 0:
                digit = mag % 20
                bars = digit // 5
                dots = digit % 5
                self.levels.append((bars, dots))
                mag //= 20

    @classmethod
    def from_bars_dots(cls, bars: int, dots: int, sign: int = 1):
        total = sign * (bars * 5 + dots)
        return cls(total)

    def glyph(self) -> str:
        """Renderiza el número en notación tradicional vertical."""
        if self.val == 0:
            return "[ 𝄐 (Caracol) ]"
        
        lines = []
        sign_str = "(-)" if self.sign < 0 else "(+)"
        lines.append(f"{sign_str} Total: {self.val}")
        
        for idx in reversed(range(len(self.levels))):
            bars, dots = self.levels[idx]
            d_str = ("• " * dots).strip() if dots > 0 else ""
            b_str = " | ".join(["——"] * bars) if bars > 0 else ""
            comp = f"{d_str} {b_str}".strip()
            if not comp:
                comp = "𝄐"
            lines.append(f"  20^{idx}: [ {comp} ]")
        return "\n".join(lines)

    def __add__(self, other: "MayaScalar") -> "MayaScalar":
        return MayaScalar(self.val + other.val)

    def __sub__(self, other: "MayaScalar") -> "MayaScalar":
        return MayaScalar(self.val - other.val)

    def __mul__(self, other: "MayaScalar") -> "MayaScalar":
        return MayaScalar(self.val * other.val)

# ======================================================================
# 2. CAPA NEURONAL VIGESIMAL
# ======================================================================

class MayaNeuron:
    """Una neurona artificial que opera con aritmética vigesimal maya."""
    def __init__(self, in_features: int):
        self.weights: List[MayaScalar] = [
            MayaScalar(random.choice([-3, -2, -1, 1, 2, 3])) for _ in range(in_features)
        ]
        self.bias: MayaScalar = MayaScalar(0)
        self.last_inputs: List[MayaScalar] = []
        self.last_z: MayaScalar = MayaScalar(0)
        self.last_a: MayaScalar = MayaScalar(0)

    def forward(self, inputs: List[MayaScalar]) -> MayaScalar:
        self.last_inputs = inputs
        accum = MayaScalar(0)
        for w, x in zip(self.weights, inputs):
            accum = accum + (w * x)
        
        self.last_z = accum + self.bias
        
